apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: datasamudaya-cluster-role
rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["create","delete","deletecollection","get","list","patch","update","watch"]
    - apiGroups:
      - ""
      resources:
      - services
      verbs: ["create","delete","deletecollection","get","list","patch","update","watch"]
    - apiGroups:
      - apps
      resources:
      - statefulsets
      verbs: ["create","delete","deletecollection","get","list","patch","update","watch"]