apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: datasamudaya-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: datasamudaya-service-account
  namespace: default
roleRef:
    kind: Role
    name: datasamudaya-cluster-role
    apiGroup: rbac.authorization.k8s.io