apiVersion: v1
kind: Service
metadata:
  name: datasamudayastandalone
  labels:
    app: datasamudayastandalone
  namespace: default
spec:
  type: NodePort
  selector:
    app: datasamudayastandalone
  ports:
    - name: streamproto
      protocol: TCP
      port: 22222
      targetPort: 22222
    - name: streamweb
      protocol: TCP
      port: 22223
      targetPort: 22223
    - name: mrproto
      protocol: TCP
      port: 11111
      targetPort: 11111
    - name: mrweb
      protocol: TCP
      port: 11112
      targetPort: 11112
    - name: sqlstream
      protocol: TCP
      port: 12123
      targetPort: 12123
    - name: sqlshell
      protocol: TCP
      port: 12124
      targetPort: 12124
    - name: pigport
      protocol: TCP
      port: 11123
      targetPort: 11123