apiVersion: v1
kind: Service
metadata:
  name: datasamudayastandalone
  labels:
    app: datasamudayastandalone
spec:
  type: NodePort
  selector:
    app: datasamudayastandalone
  ports:
    - name: streamproto
      protocol: TCP
      port: 22222
      targetPort: 22222
      nodePort: 32000
    - name: streamweb
      protocol: TCP
      port: 22223
      targetPort: 22223
      nodePort: 32001
    - name: mrproto
      protocol: TCP
      port: 11111
      targetPort: 11111
      nodePort: 32002
    - name: mrweb
      protocol: TCP
      port: 11112
      targetPort: 11112
      nodePort: 32003
    - name: sqlstream
      protocol: TCP
      port: 12123
      targetPort: 12123
      nodePort: 32004
    - name: sqlshell
      protocol: TCP
      port: 12124
      targetPort: 12124
      nodePort: 32005
    - name: pigport
      protocol: TCP
      port: 11123
      targetPort: 11123
      nodePort: 32006
    - name: datanode
      protocol: TCP
      port: 9864
      targetPort: 9864