apiVersion: v1
kind: Service
metadata:
  name: zoo
  labels:
    app: datasamudayazk
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: datasamudayazk
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181