apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datasamudayazk
  labels:
    app: datasamudayazk
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasamudayazk
  template:
    metadata:
      labels:
        app: datasamudayazk
    spec:
      serviceAccountName: datasamudaya-service-account
      containers:
        - name: datasamudayazk
          image: arunsrajan/datasamudayazk:latest
          resources:
              requests:
                memory: "64Mi"
                cpu: "1"
              limits:
                memory: "1024Mi"
                cpu: "1"
          env:
            - name: PODCIDRNODEMAPPINGENABLED
              value: "true"
            - name: DATASAMUDAYA_HOME
              value: /opt/datasamudaya
          ports:
            - containerPort: 2181
              name: zkport
          volumeMounts:
            - name: hdfsdatanode
              mountPath: /opt/dockershare/data
  volumeClaimTemplates:
        - metadata:
            name: hdfsdatanode
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi