apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hadoop-hdfs-namenode
  labels:
    app: hadoop-hdfs-namenode
spec:
  selector:
    matchLabels:
      app: hadoop-hdfs-namenode
  serviceName: namenode
  template:
    metadata:
      labels:
        app: hadoop-hdfs-namenode
    spec:
      serviceAccountName: datasamudaya-service-account
      nodeSelector:
        namenode: "true"
      containers:
        - name: hadoop-hdfs-namenode-container
          image: arunsrajan/hadoop-namenode:2.0.0-hadoop3.1.3-java8
          resources:
              requests:
                cpu: "250m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "1024Mi"
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CORE_CONF_fs_defaultFS
              value: "hdfs://$(HOST_IP):9000"
            - name: HDFS_CONF_dfs_namenode_http___address
              value: "$(HOST_IP):9870" 
            - name: CLUSTER_NAME
              value: hadoopcluster
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_permissions_enabled
              value: "false"
      hostNetwork: true